# Site settings
title: Next Craft
email: next-craft-org@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Next Craft is an open-source builder collective. In 2026 we craft agents,
  tools, and applied AI in public — so member ideas reach daylight.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nextcraft.org" # the base hostname & protocol for your site
twitter_username: nextcraftorg
github_username:  nextcraft

# Build settings
markdown: kramdown
